FROM nginx:1.25

RUN rm -f /etc/nginx/conf.d/* /etc/nginx/nginx.conf /etc/nginx/default.conf

ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./nginx/default.conf /etc/nginx/conf.d/default.conf


# ビルド完了後にNginxを起動
CMD ["/usr/sbin/nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]