development:
  adapter: async

test:
  adapter: test

production:
  adapter: async
  url: redis://localhost:6379/1
  # url: <%= ENV['REDIS_URL'] %>
  # port: 6379
  # channel_prefix: conveni_friends_production
